name: build

on:
  workflow_call:
    inputs:
      mainPipeline:
        description: Distinguish main and PR pipelines
        default: false
        required: false
        type: boolean
      prNumber:
        description: Pull request number
        required: false
        type: number

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Generate Jacoco report
      run: mvn jacoco:report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: target/site/jacoco/jacoco.xml
        fail_ci_if_error: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      if: ${{ inputs.mainPipeline }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      if: ${{ inputs.mainPipeline }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      if: ${{ inputs.mainPipeline }}
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/my-spring-boot-app:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/my-spring-boot-app:pr-${{ inputs.prNumber }}
